wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/cnn_image_classifier.py
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1648553466
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 16
      4: 3.10.2
      5: 0.12.10
      8:
      - 3
      - 5
architecture_params:
  desc: null
  value:
    activation_cnn: relu
    activation_fc: sigmoid
    batch_norm_loc: before
    dense_neurons: 100
    kernel_size: 3
    net_loss_func: mean_square_error
    num_cnn_layers: 5
    num_filters:
    - 16
    - 32
    - 64
    - 128
    - 256
    optimiser: adam
    pool_kernel: 2
    weight_initialisation: random
training_params:
  desc: null
  value:
    batch_size: 32
    data_augmentation: 'False'
    data_split: 0.8
    dropout: 0.2
    epochs: 10
    learning_rate: 0.0001
    lr_decay_factor: 0
