wandb_version: 1

activation_cnn:
  value: selu
batch_size:
  value: 64
data_augmentation:
  value: 'False'
epochs:
  value: 60
learning_rate:
  value: 0.001
num_filters:
  value:
  - 32
  - 64
  - 128
  - 256
  - 512
