wandb_version: 1

activation_cnn:
  value: elu
activation_fc:
  value: sigmoid
batch_size:
  value: 103
data_augmentation:
  value: 'True'
data_split:
  value: 0.6837809779569939
dense_neurons:
  value: 133
dropout:
  value: 0.15454584094934368
epochs:
  value: 64
kernel_size:
  value: 2
learning_rate:
  value: 0.00018303808626404913
optimiser:
  value: adam
