wandb_version: 1

activation_cnn:
  value: relu
activation_fc:
  value: sigmoid
batch_norm_loc:
  value: before
batch_size:
  value: 51
data_augmentation:
  value: 'False'
data_split:
  value: 0.6556924268345963
dense_neurons:
  value: 159
dropout:
  value: 0.33867954874951356
epochs:
  value: 15
kernel_size:
  value: 3
learning_rate:
  value: 0.00012533476535256705
net_loss_func:
  value: mean_square_error
num_cnn_layers:
  value: 8
optimiser:
  value: adam
weight_initialisation:
  value: random
