wandb_version: 1

activation_cnn:
  value: selu
batch_size:
  value: 128
data_augmentation:
  value: 'True'
epochs:
  value: 30
learning_rate:
  value: 0.0001
num_filters:
  value:
  - 32
  - 32
  - 32
  - 32
  - 32
